import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import Nav from '@/components/ui/nav'
import { SearchMachineProvider } from '@/context/search-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <SearchMachineProvider>
            <main className="mx-auto flex min-h-screen max-w-7xl flex-col px-24">
              <Nav></Nav>
              {children}
            </main>
          </SearchMachineProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
